### ISSUE TITLE
Tag 1.1.1 fails with the error "SyntaxError: Use of const in strict mode"

### ISSUE THREAD

**Issue by sharathrocks** [kevva/lpad-align#4]
The latest tag 1.1.0 fails with an error:
`const indentString = require('indent-string');
00:02:48.098 ^^^^^
00:02:48.099 SyntaxError: Use of const in strict mode.
00:02:48.099     at Module._compile (module.js:439:25)
00:02:48.099     at Object.Module._extensions..js (module.js:474:10)
00:02:48.099     at Module.load (module.js:356:32)
00:02:48.099     at Function.Module._load (module.js:312:12)
00:02:48.099     at Module.require (module.js:364:17)
00:02:48.099     at require (module.js:380:17`
npm module logalot uses squeak which in turn uses lpad-align. Installation of logalot fails due to this on my machine.
Request you to please have a look.

**Comment by hkailantzis** [comment]
confirm same issue here, with node v0.12.x. please fix.

**Comment by briansneddon** [comment]
Suggest releasing these changes as a major version bump and not a patch level (or even a minor) and backing out this current 1.1.1 patch level release.

**Comment by kevva** [comment]
Sorry guys, I forgot I introduced some breaking changes while not bumping the version a while ago. I'll revert and do a major.

**Comment by kevva** [comment]
Should be fixed in `1.1.2`.
